### ISSUE TITLE
Session Sequence States

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/walletconnect#11]
Previously we have had the following Session Sequence states defined by Behavioural Logic:

|  Pending 	| Settled  	|  
|---	|---	|
|   proposed / responded	|   	presettled / acknowledged|   	  	

Each of the sequences had different properties based on exchanged data and different `ttl`s:

```
    static var timeToLiveProposed: Int {
        Time.hour
    }
    
    static var timeToLivePending: Int {
        Time.day
    }
    
    static var timeToLiveSettled: Int {
        Time.day * 7
    }
```

Now we should define new naming for Session Sequence states and define their `ttl`s

|  Proposed 	| Settled  	|  
|---	|---	|
|   requested / responded	|   	settled|   	  

The following states are recognised on clients:

1. Dapp

|  State 	| Condition  	|  
|---	|---	|
|  Proposed-requested	|   	dapp sends `wc_sessionPropose` request|   	
|  Proposed-responded	|   	dapp receives `wc_sessionPropose` response|   	
|  Settled	|   	dapp receives `wc_sessionSettle` request|   	

2. Wallet

|  State 	| Condition  	|  
|---	|---	|
|  Proposed-responded	|   	wallet respond on `wc_sessionPropose` request|   	
|  Settled	|   	wallet sends `wc_sessionSettle` request|   	

suggested expiry times:

Proposed-requested - 1h
Proposed-responded - 1h
Settled - 7days

**Comment by llbartekll** [comment]
@WalletConnect/sdk-team ⬆️

**Comment by jakubuid** [comment]
On my side it looks fine.

**Comment by jakubuid** [comment]
@pedrouid @llbartekll guys pls put a summary on what we decided on

**Comment by pedrouid** [comment]
Here is my take on it.

The Engine should have three stores: Pairing, Proposal, Session

However only Pairing and Session will have corresponding topics that are subscribed by the Relayer and therefore have expiry values 

Proposal doesn't necessarily have an expiry but it could potentially have in the future one to be cleared from storage.

Here is how see the different states

Proposal is proposed when the dapp sends wc_sessionPropose and similarly on the wallet when message is received

Proposal is responded when the wallet sends a response (approval or rejection) and similarly on the dapp when message is received

(at this point there is a small window of time where responded state is only relevant until the next steps that happens almost immediately after)

Session is pre-settled when the wallet sends a wc_sessionSettle and similarly on the dapp when message is received

Session is acknowledged (aka settled) when the dapp sends a response (success or failure) and similarly on the wallet when message is received

These states are very similar to the ones we had before and the first two are sent through topic A (pairing) and the last are sent through topic B (session)

I'm not particularly in favor of having a different expiry between pre-settled and settled (seems error-prone to me)

**Comment by llbartekll** [comment]
I like it - super simplified

**Comment by jakubuid** [comment]
One question:
Is the storage really needed for proposals? Imo it should be enough to just store them in map or dictionary.

**Comment by llbartekll** [comment]
As we discussed, I think it is not very painful to lose proposal on app crash but it simplifies a lot.

**Comment by llbartekll** [comment]
just one small thing: what you guys prefer:
`preSettled/Settled`
`unacknowledged/acknowledged`
mix of two above?
I think they mean the same, so it would be better to avoid double terms for one concept in docs and conversations.

**Comment by jakubuid** [comment]
Yea I agree. I prefer: `unacknowledged/acknowledged`.
The third option is a flag. Let's discuss it on call.

**Comment by jakubuid** [comment]
unacknowledged/acknowledged for sessions state

**Comment by chadyj** [comment]
From the call:

In case of sessions, use unacknowledged/acknowledged flag
In case of proposals, it is up to the teams
Stop using settled

**Comment by pedrouid** [comment]
PR required to include spec for defining these states

**Comment by chadyj** [comment]
@WalletConnect/sdk-team Who wants to volunteer for this PR?
