### ISSUE TITLE
CACAO support

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/walletconnect#17]
Discussion from the weekly meeting:

- Good API should have at least 1 required parameter
- Eg update blockchain, or update accounts
- Accounts are a required parameter. Signature is optional
- Idea: Accounts are objects instead of strings
- https://github.com/ChainAgnostic/CAIPs/pull/74
- Decision for new name: “Update accounts”

Details to be discussed

@WalletConnect/sdk-team 

**Status**

Updated in:

- [ ] JS
- [ ] Swift
- [ ] Kotlin

**Comment by pedrouid** [comment]
Now known as Auth API
