### ISSUE TITLE
Sticky Client IDs

### ISSUE THREAD

**Issue by arein** [WalletConnect/walletconnect#60]
**What**
The [v2 backend](https://docs.google.com/document/d/1ArOyT9mkSDk0FL9yCpWogxYPduQ04nzXH0dTaCBoQoM/edit) introduces a concept of mailboxes. Every client has a dedicated mailbox. Messages that cannot be delivered when recipients are offline will be delivered to their mailboxes. Once they reconnect they pick up their mail.

This requires a sticky identifier (i.e. the mailbox address) for clients which clients present upon reconnection.

**Implementation**
Should no `client id` HTTP header be present during websocket connection upgrade we will set one via a cookie. SDK stores the cookie and presents the client ID in the HTTP handshake header upon reconnection.

**Uniqueness**
Client IDs should not collide. For us a GUID is good enough. But we are happy to use more sophisticated mechanisms.
We could also use the public key of the wallet which could then be signed for an auth layer.

**Security/Threat Vectors**
* Spoofing: should Alice's client-id be spoofed by Bob he may retrieve her mailbox content and she might not receive some messages. Bob however will not be able to ACK the messages. So the system is still in sync. Bob can also not read the contents of the messages

**FAQ**
* What is a client? Any instance of the SDK e.g. a dapp or a specific wallet. It is not a device identifier/fingerprint. Once device may have multiple client ids
* How about the initial pairing? During initial pairing there may not be a client id yet. In that case 
* Will you leverage this for sticky load balancer sessions? Potentially, yes, as an optimization

**Status**

- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/263
- [x] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/189
- [x] https://github.com/WalletConnect/walletconnect-monorepo/issues/1143
- [x] https://github.com/WalletConnect/ts-relay/issues/7

**Comment by llbartekll** [comment]
@arein to recap our conversation:
- In order to create client ID, client generates public/private key pair.
- public key is recognised by the server as client ID.
- to eliminate a thread of spoofing, client must authenticate on every web socket handshake
- to authenticate means - sign a challenge with private key associated with client ID(public key)
- a challenge could be a hash of current timestamp +/-1minute
- server can empty the mailbox and consider messages delivered to mailbox owner only on client's acknowledges during authenticated websocket session

**Comment by arein** [comment]
What is the right way to get this work prioritized?

**Comment by arein** [comment]
How do we store the client id on the browser?

**Comment by llbartekll** [comment]
> How do we store the client id on the browser?

same as session keys etc.?

**Comment by chadyj** [comment]
Decision:
Implement client ID's for beta 102.
This will be mocked on the server, but required to prevent breaking changes in the future.

Client id is required for cross-node functionality.
@WalletConnect/sdk-team

**Comment by chadyj** [comment]
@arein Teams are ready to add this, but we need to add the details to the spec before implementation.  Then we can ship with beta 102.

**Comment by chadyj** [comment]
Related:

https://gist.github.com/pedrouid/a09452a25b0dbf90ee269601874554a7

**Comment by pedrouid** [comment]
So the proposed solution is to add an HTTP endpoint to the Relay Server that would return a Client authentication nonce. This nonce would match what we currently have as socketId in the Typescript source code
 
 The HTTP endpoint would be the following `GET /auth-nonce` would return a JSON response like for example
 ```
 {
    "nonce": "c479fe5dc464e771e78b193d239a65b58d278cad1c34bfb0b5716e5bb514928e"
}
```

From this nonce, the clients would sign it as prefixed message as described in the following gist:
https://gist.github.com/pedrouid/a09452a25b0dbf90ee269601874554a7

The signature would be used for authentication as header params for the WebSocket:
* nonce (provided by server)
* publicKey (aka client id)
* signature (signed nonce)

The server would then validate that the nonce was signed correctly and it matches the provided publicKey.

The WebSocket would be successfully open and it would be able to use the JSON-RPC API as before

**Comment by pedrouid** [comment]
The above spec is just too similar to JWT for me to feel comfortable to be doing our own implementation

In fact JWT supports Ed25519 signing which is labelled as "eddsa" and we could map the parameters that we currently have as equivalents for JWT

nonce -> subject (sub)
clientId -> issuer (iss)

We also have two other recommended claims which are expiration (exp) and audience (aud) but I think that they are unnecessary for now and we could start simple by defining the following JWT struct

HEADER
```json
{
  "alg": "EdDSA",
  "typ": "JWT"
}
```

PAYLOAD
```json
{
  "iss": "884ab67f787b69e534bfdba8d5beb4e719700e90ac06317ed177d49e5a33be5a"m
  "sub": "c479fe5dc464e771e78b193d239a65b58d278cad1c34bfb0b5716e5bb514928e"
}
```

This would be really advantageous to simplify Authentication for the headers since JWT can be represented as simple bearer tokens

```
Authorization: Bearer <token>
```

**Comment by pedrouid** [comment]
Ok after tweaking back and forth some stuff I'm close to replacing the previous implementation with a JWT-compatible version that uses ed25519

```typescript
import * as ed25519 from '@stablelib/ed25519';
import { fromString } from 'uint8arrays/from-string';
import { toString } from 'uint8arrays/to-string';

function toBase64Url(val: any): string {
  return toString(fromString(JSON.stringify(val), 'utf8'), 'base64url')
}

async function signJWT(subject: string, keyPair: ed25519.KeyPair) {
  const header = {
    "alg": "EdDSA",
    "typ": "JWT"
  }
  const issuer = toString(keyPair.publicKey, "hex")
  const payload = {
    "iss": issuer,
    "sub": subject,
  }
  let params = [toBase64Url(header), toBase64Url(payload)]
  const signature = ed25519.sign(keyPair.secretKey, fromString(params.join('.'), 'utf8'))
  params.push(toBase64Url(signature))
  return params.join('.')
}

```

Just need to create the verifyJWT() function and then test it with other JWT verifiers

**Comment by arein** [comment]
https://github.com/WalletConnect/ts-relay/issues/7 for us to create the `HTTP GET /auth-nonce` endpoint that sends a nonce.

```
{
   "nonce": "c479fe5dc464e771e78b193d239a65b58d278cad1c34bfb0b5716e5bb514928e"
}
```

and to expect a

```
Authorization: Bearer <token>
```

header upon websocket handshake.

**Comment by chadyj** [comment]
Todo:
@llbartekll and @arein to do the spec PR

**Comment by pedrouid** [comment]
I've finalized the gist in Typescript that implements JWT authentication with ed25519 for our Relays

This is much leaner and ad-hoc than using a JWT library and allows us to use our own cryptographic libraries to be compatible

I will publish a NPM package for this that can be shared between JS clients and TS relay-server

https://gist.github.com/pedrouid/ae5cb3a55dd07f7fc63b60117242dba9


Also this should be easier to interpret and replicate for Swift and Kotlin clients

**Comment by arein** [comment]
See #66

**Comment by pedrouid** [comment]
I've updated the gist for the JWT authentication to comply with `did:key` method that requires base58 multicodec

**Comment by llbartekll** [comment]
what do you think if we do:
PAYLOAD:
```
{
   iss: did:key:xxxx
   sub: String
   iat: Date
   exp: Date
}
```
`exp`: could be ~7days? 
This way client could easily control expiry and reissue new token when needed without 401 errors.
