### ISSUE TITLE
Granular Tags

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/walletconnect#84]
Right now we have implemented iridium_publish tags as an integer that identifies each API: Unknown(0), Sign (1), Chat (2), Auth (3), Push (4)

However we want to move into more Granular tags per each JSON-RPC method to improve our network metrics to ensure users can successfully complete API-specific flows

This would look as follows for Sign API and Chat API:

------ SIGN -----

* wc_pairingDelete -> req: 1000 / res: 1001
* wc_pairingPing -> req: 1002 / res: 1003
* wc_sessionPropose -> req: 1100 / res: 1101
* wc_sessionSettle -> req: 1102 / res: 1103
* wc_sessionUpdate -> req: 1104 / res: 1105
* wc_sessionExtend -> req: 1106 / res: 1107
* wc_sessionRequest -> req: 1108 / res: 1109
* wc_sessionEvent -> req: 1110 / res: 1111
* wc_sessionDelete -> req: 1112 / res: 1113
* wc_sessionPing -> req: 1114 / res: 1115

------ CHAT -----

* wc_chatInvite -> req: 2000 / res: 2001
* wc_chatMessage -> req: 2002 / res: 2003
* wc_chatLeave -> req: 2004 / res: 2005
* wc_chatPing -> req: 2006 / res: 2007

These should be part of the spec of each API so that Relay and SDK are in sync

Todo:

- [x] https://github.com/WalletConnect/walletconnect-specs/pull/86
- [x] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/249
- [x] https://github.com/WalletConnect/walletconnect-monorepo/issues/1242
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/330
- [x] https://github.com/WalletConnect/ts-relay/issues/213
- [ ] https://github.com/WalletConnect/rs-relay/issues/122

**Comment by llbartekll** [comment]
should we add?

------ AUTH -----

wc_authRequest -> req: 3000 / res: 3001
