### ISSUE TITLE
User-Agent SDK support

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/walletconnect#85]
## Problem

It is currently impossible to understand SDK version adoption and usage.

Knowing adoptions helps us make future product decisions.  For example,  we may want to deprecate SDK versions, or make breaking changes, so knowing adoption will be a driver in decisions. 

## Solution

Add a `user-agent` to the clients, and collect this in our metrics.

Later, we can even surface version information in the Cloud dashboard and inform users about new updates and breaking changes.

## Format

User agents typically have the following format:

`User-Agent: <product> / <product-version> <comment>`

Some examples:

`Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0`
`curl/7.64.1`
`Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`

Proposals?

`WalletConnect Sign/2.0-beta.1`

Todo
- [x] https://github.com/WalletConnect/walletconnect-specs/pull/87
- [x] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/250
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/331
- [x] https://github.com/WalletConnect/walletconnect-monorepo/issues/1241
- [x] https://github.com/WalletConnect/ts-relay/issues/204
- [ ] https://github.com/WalletConnect/rs-relay/issues/121

**Comment by pedrouid** [comment]
We currently have a very similar structure for Javascript which we could change honestly to make it more platform agnostic

Whenever a Websocket client is created we add a few url params to the URL:

```
# Browser
    protocol = "wc"
    version = 2
    env = "browser"
    host = "app.uniswap.com"

"wss://relay.walletconnect.com" + "?protocol=wc" + "&version=2" + "&env=browser" + "&host=app.uniswap.com"

# NodeJS
    protocol = "wc"
    version = 2
    env = "node"
    host = undefined

"wss://relay.walletconnect.com" + "?protocol=wc" + "&version=2" + "&env=node"

# React-Native
    protocol = "wc"
    version = 2
    env = "react-native"
    host = undefined

"wss://relay.walletconnect.com" + "?protocol=wc" + "&version=2" + "&env=react-native"
```

Essentially we should be able to format all these 4 params very similarly across Web, Android and iOS plus potentially adding more information about the Operating System as well.

**Comment by Elyniss** [comment]
I like the idea of specifying platform/env.
Should we specify every SDK version at web-socket client creation? If not is there any other way to describe the version at webclient creation?

```
# React-Native
    protocol = "wc"
    sign-version = beta102
    another-sdk-version = alpha4
    env = "react-native"
    host = undefined
```

**Comment by Elyniss** [comment]
Wouldn't it be better to use the HTTP `user-agent` header for this instead of URL params?

**Comment by pedrouid** [comment]
Required params for User Agent:

* Protocol Version (protocol) - defines WalletConnect protocol version (eg. "wc-relay-2.0")
* SDK Version (sdk) - defines which SDK is being used (eg. "swift-2.0-rc.0" or "js-2.0-rc.0" or "kotlin-2.0-rc.0")
* Operating System (os) - defines which operating system is being used (eg "macos-12.4")

Optional params for User Agent:

* App identifier (id) - defines which application is being used (eg "browser-app.uniswap.org" or "android-com.walletconnect.example")
