### ISSUE TITLE
Add deep link to controller meta data

### ISSUE THREAD

**Issue by jakubuid** [WalletConnect/walletconnect#95]
Hey @sdk-team we got interesting feedback from OpenSea. If I recall this feature was also requested by Argent team.

**Problem:**
Given that a user has multiple wallets installed on an Android mobile device and there is a session established between a Dapp and one of the wallets. Dapp wants to send a session request to the wallet via deep-link. Every-time the Dapp sends a session request, Android system shows app chooser with all wallets installed on the device. It creates a point of failure for the user to choose the wrong wallet (a wallet that is not connected).

**Solution:**
The wallet needs to provide a Dapp with either a wallet specific deep-link scheme or its package name. Where Dapp will be able to call directly already connected wallet when sending session request via deep-link.

**PR:** 
https://github.com/WalletConnect/walletconnect-specs/pull/94

**Next:**
Improve v2 documentation and add a section describing the deep-link flow on Android devices.

**Questions:** 
- Is this feature apply on iOS devices? - Afaik, no. @WalletConnect/swift-team can you confirm?

**Comment by llbartekll** [comment]
for iOS and universal linking AppMetadata's url should be enough to open the wallet.

**Comment by llbartekll** [comment]
`If I recall this feature was also requested by Argent team.` I think Argent was requesting custom fields, like a map [string: any] or something similar.

**Comment by pedrouid** [comment]
There has been a pattern created for this between Zerion and Rainbow teams

They added an optional field to the AppMetadata called `scheme`... this doesn't mean that is the correct way of doing this but we should essentially follow a similar pattern

While this solution was used for a wallet to redirect back to the dapp it can also be used vice-versa

We just need to make a decision on how, when and where to handle this since in the past we have made this a responsibility to the SDK consumer but it would be hard to do so for every signing request

**Comment by jakubuid** [comment]
> `If I recall this feature was also requested by Argent team.` I think Argent was requesting custom fields, like a map [string: any] or something similar.

Yes you are right, they were requesting some custom fields and deepLink schema as well. I'll create another issue for that.


> We just need to make a decision on how, when and where to handle this since in the past we have made this a responsibility to the SDK consumer but it would be hard to do so for every signing request

So having the `deepLink` field in the peerMetaData in the Session object should resolve problem with redirecting from Wallet to Dapp and vice-versa.

From Wallet perspective peerMetaData.deepLink will be a schema pointing to native Dapp.
From Dapp perspective peerMetaData.deepLink will be a schema pointing to native Wallet.

Wallet receives Dapp's metaData from session proposal.
Dapp receives Wallet's metaData on session settle.

Imo it shouldn't be so hard to do it on every request. When Dapp sends a session request to Wallet it already knows the session topic so it is only matter of filtering the given session by topic and calling the intent with proper deep-link schema.

We could treat this as default behaviour and the current generic deep-link implementation as a fallback.

**Comment by pedrouid** [comment]
Using the same pattern as the Explorer API we can introduce a new optional param called "redirect" to the AppMetadata interface
```jsonc
{
  "name": string,
  "description": string,
  "url": string,
  "icons": [string],
  "redirect": { // Optional
    "native": string, // Optional
    "universal": string, // Optional
  }
}
```

**Comment by jakubuid** [comment]
Changes merged with: https://github.com/WalletConnect/walletconnect-specs/pull/94
